language: lua
before_install:
  - sudo apt-get install lua5.1
script: ant clean package
deploy:
  provider: packagecloud
  username: opussf
  token: 54138e81e09e8f005ae297f5298cfd6f45a1b82e110aa2bf
  dist: all
  local-dir: target
  on:
    branch: master